### ISSUE TITLE
RTOS installation is not working properly

### ISSUE THREAD

**Issue by praj441** [UT-Austin-RPL/deoxys_control#12]
Hi,

Thanks for the great work. Unfortunately, I am not able to work-with properly the RTOS on the NUC-11.
The precompiled rt-lernel-5.11.4-rt11 doesn't seems to be compatible with NUC hardware. 
The speed is slow and the ethernet is not working which is essential for the robot.

Can you provide or direct towards the newer precompiled rt kernel versions.

**Comment by zhuyifengzju** [comment]
Hi,
Since I am not sure the situation of hardware you are using and do not have the exact hardware to reproduce your issue, it's unclear if it's an installation issue or something else. I've provided details on compiling RTOS on your own: https://zhuyifengzju.github.io/deoxys_docs/html/installation/system_prerequisite.html?highlight=rtos. Let me know if the issue continues if you've compiled on your own. However, if you are talking about "speed is slow" when using GUI, that could happen. I believe if you use ssh only, the GUI speed will no longer be an issue.

If it's ethernet not working, I believe you need to add additional firmware patch to enable ethernet connection.

**Comment by praj441** [comment]
@zhuyifengzju 
Thanks for the prompt response.
Currently, I have another machine where the RTOS installation is working fine.
I compiled another kernel, which is 5.14.2-rt21 on NUC-11. The slow-down process disappears, but the Ethernet one remains.
I will try the firmware patch thing for Ethernet. If you have any idea where to get the appropriate firmware patch, please let me know.

Thanks!

**Comment by zhuyifengzju** [comment]
It's been a while since I am dealing with this issue. I believe something like [this](https://www.intel.com/content/www/us/en/download/739770/intel-ethernet-lan-network-connection-driver-for-windows-10-64-bit-and-windows-11-for-intel-nuc-12-pro-kits-mini-pcs-nuc12ws.html) is what you need.

**Comment by praj441** [comment]
Okay. Thanks. I will try this.
