### ISSUE TITLE
How to merge nuc to desktop?

### ISSUE THREAD

**Issue by cheerful11** [UT-Austin-RPL/deoxys_control#26]
I just have one machine. How can I run all the code in my PC without NUC.

**Comment by zhuyifengzju** [comment]
It depends on if your PC is only for control purpose or if you need to use GPUs. If you need to use GPUs, merging is not a solution because the real-time kernel is not compatible with Nvidia drivers. If you do not need GPUs, you can just install real time kernel on your PC and install both c++ and python code on the same machine.
