### ISSUE TITLE
Collision detection

### ISSUE THREAD

**Issue by GitMichaelR** [UT-Austin-RPL/deoxys_control#27]
Hello, 

is there a way to register if the robot arm is colliding with something? Like is there a metric with which I can say: if the value is greater than ..., then  go to start position.

Thanks in advance!

**Comment by zhuyifengzju** [comment]
Hi,
Currently I don't have the code implemented for collision detection. You can get the torque information of joints by reading the states. However, I don't think there is a easy way to specify that, because the statistics of detecting collision is actually non-trivial. There is a work specifically on this topic: https://arxiv.org/pdf/2011.03142.
